name: pyleoclim_stable
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.20.1
  - jupyter=1.0.0
  - xarray=0.19.0
  - netCDF4=1.5.7
  - Bottleneck=1.3.2
  - dask=2021.9.1
  - climlab=0.7.12
  - pip
  - python=3.9.7
  - pandas=1.3.3
  - numpy=1.21.2
  - matplotlib=3.4.3
  - scipy=1.7.1
  - seaborn=0.11.1
  - scikit-learn=0.24.2
  - statsmodels=0.12.2
  - numba=0.53.1
  - nitime=0.9
  - pip:
    - pyleoclim==0.7.3
    - jupytemplate==0.3.0
